# Welcome to Jekyll!

# Website settings
title: "roto's dev zone"
description: "jekyll test"
keywords: "javascript,html,web,react.js,angular.js"
baseurl: ""
url: "https://rotoshine.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'roto'
  first_name: 'TaeHee'
  last_name: 'Kim'
  email: 'winterwolf0412@gmail.com'
  facebook_username: 'rotoshine'
  github_username: 'rotoshine'
  head_img: 'static/img/landing/roto.jpg'
  desc: 'I am a Javascript engineer with website development, automation Ops and writing scripts experience. Life is a continuous learning process, so work makes me more rigorous, travel makes my life more colorful. I can make lots of friends when I coding and travel.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  - locale: 'ko'
    flag: 'static/img/flags/South-Korea.png'

# blog img path
img_path: '/static/img/blog'

# comment

disqus:
  name: winterwolf0412
  public_key: eGlagthWw2PoOLoPxMewVuqQRKiQLDMBTN4tIC39JfkH4IDN1Zq70s3Ll4TmmhU4

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
